# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movielist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='profile',
        ),
        migrations.AddField(
            model_name='movie',
            name='users',
            field=models.ManyToManyField(related_name='movies', related_query_name='movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
